import { ChannelTypes } from './channelTypes';

export const disclaimerText = {
  id: "Angka ini hanya contoh. Biaya platform bisa berbeda tergantung kontrak, promo, dan kebijakan terbaru.",
  en: "This is only an example. Platform fees may differ depending on contract, promotion, and latest policy."
};

export const defaultChannelProfiles = [
  {
    id: "preset-offline",
    version: 1,
    name: "Offline / Direct",
    type: ChannelTypes.OFFLINE,
    provider: "offline",
    commissionPercent: 0,
    paymentFeePercent: 0,
    paymentFeeFixed: 0,
    additionalPackagingCost: 0,
    sellerPromoPercent: 0,
    sellerPromoFixed: 0,
    consignmentFeePercent: 0,
    fixedChannelCost: 0,
    notes: "",
    isPreset: true,
    source: "preset",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "preset-gofood",
    version: 1,
    name: "GoFood (Contoh)",
    type: ChannelTypes.MARKETPLACE,
    provider: "gofood",
    commissionPercent: 20,
    paymentFeePercent: 0,
    paymentFeeFixed: 0,
    additionalPackagingCost: 0,
    sellerPromoPercent: 0,
    sellerPromoFixed: 0,
    consignmentFeePercent: 0,
    fixedChannelCost: 0,
    notes: disclaimerText.id,
    isPreset: true,
    source: "preset",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "preset-grabfood",
    version: 1,
    name: "GrabFood (Contoh)",
    type: ChannelTypes.MARKETPLACE,
    provider: "grabfood",
    commissionPercent: 20,
    paymentFeePercent: 0,
    paymentFeeFixed: 0,
    additionalPackagingCost: 0,
    sellerPromoPercent: 0,
    sellerPromoFixed: 0,
    consignmentFeePercent: 0,
    fixedChannelCost: 0,
    notes: disclaimerText.id,
    isPreset: true,
    source: "preset",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "preset-shopeefood",
    version: 1,
    name: "ShopeeFood (Contoh)",
    type: ChannelTypes.MARKETPLACE,
    provider: "shopeefood",
    commissionPercent: 20,
    paymentFeePercent: 0,
    paymentFeeFixed: 0,
    additionalPackagingCost: 0,
    sellerPromoPercent: 0,
    sellerPromoFixed: 0,
    consignmentFeePercent: 0,
    fixedChannelCost: 0,
    notes: disclaimerText.id,
    isPreset: true,
    source: "preset",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "preset-reseller",
    version: 1,
    name: "Reseller (Contoh)",
    type: ChannelTypes.RESELLER,
    provider: "custom",
    commissionPercent: 0,
    paymentFeePercent: 0,
    paymentFeeFixed: 0,
    additionalPackagingCost: 0,
    sellerPromoPercent: 0,
    sellerPromoFixed: 0,
    consignmentFeePercent: 0,
    fixedChannelCost: 0,
    notes: "Owner margin: 30%, Reseller margin: 25%",
    isPreset: true,
    source: "preset",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "preset-consignment",
    version: 1,
    name: "Titip Jual (Contoh)",
    type: ChannelTypes.CONSIGNMENT,
    provider: "custom",
    commissionPercent: 0,
    paymentFeePercent: 0,
    paymentFeeFixed: 0,
    additionalPackagingCost: 0,
    sellerPromoPercent: 0,
    sellerPromoFixed: 0,
    consignmentFeePercent: 20,
    fixedChannelCost: 0,
    notes: "Bagi hasil toko 20%",
    isPreset: true,
    source: "preset",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];
